import { ILabelsPack } from "./../interfaces/ILabelsPack";

export const LABELS: ILabelsPack[] = [
  {
    intl: "en-EN",
    labels: {
      AMIUTH_SPAN: "Azimuth span:",
      CURRENT_ALTITUDE: "Sun altitude:",
      CURRENT_TIME: "Current Time:",
      CURRENT_AZIMUTH: "Current Azimuth (yellow):",
      LATITUDE: "Latitude:",
      LONGITUDE: "Longitude:",
      PROGRESS: "Progress:",
      SHADOW_LENGTH: "Shadow length factor:",
      SOLARNOON_TIME: "Noon Time:",
      SOLARNOON_AZIMUTH: "Noon Time (black):",
      SUNRISE_TIME: "Sunrise Time:",
      SUNRISE_AZIMUTH: "Sunrise Azimuth (green):",
      SUNSET_TIME: "Sunset Time:",
      SUNSET_AZIMUTH: "Sunset Azimuth (red):",
      UTC_OFFSET: "UTC device offset:",
      DAWN: "Civil twilight begins (dawn):",
      DUSK: "Civil twilight ends (dusk):",
      NAUTICAL_DAWN: "Nautical twilight begins:",
      NAUTICAL_DUSK: "Nautical twilight ends:",
      NIGHT_START: "Astronomical twilight begins:",
      NIGHT_END: "Astronomical twilight ends:",
      NADIR: "Midnight (nadir):",
    },
  },
  {
    intl: "pl-PL",
    labels: {
      AMIUTH_SPAN: "Dzienny przedział:",
      CURRENT_ALTITUDE: "Wysokość słońca:",
      CURRENT_TIME: "Bieżący czas:",
      CURRENT_AZIMUTH: "Bieżący azymut (żółty):",
      LATITUDE: "Szerokość geograficzna:",
      LONGITUDE: "Długość geograficzna:",
      PROGRESS: "Postęp:",
      SHADOW_LENGTH: "Współczynnik dla cienia:",
      SOLARNOON_TIME: "Południe słoneczne:",
      SOLARNOON_AZIMUTH: "Azymut w południe (czarny):",
      SUNRISE_TIME: "Wschód słońca:",
      SUNRISE_AZIMUTH: "Azymut przy wschodzie (zielony):",
      SUNSET_TIME: "Zachód słońca:",
      SUNSET_AZIMUTH: "Azymut przy zachodzie (czerwony):",
      UTC_OFFSET: "UTC urządzenia:",
      DAWN: "Początek zmierzchu cywilnego (świt):",
      DUSK: "Koniec zmierzchu cywilnego (zmierzch):",
      NAUTICAL_DAWN: "Początek zmierzchu żeglarskiego:",
      NAUTICAL_DUSK: "Koniec zmierzchu żeglarskiego:",
      NIGHT_START: "Początek zmierzchu astronomicznego:",
      NIGHT_END: "Koniec zmierzchu astronomicznego:",
      NADIR: "Środek nocy (nadir):",
    },
  },
];
